let b = 2;

try {
    a = 1 + b; 
  
} catch (error) {
  console.log("Algo deu errado: " + error);
  
}

console.log( "O valor Ã©: " + a );
console.log("fim do programa!")